import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider"
import Header from "@/components/custom/Header"
import ConvexClientProvider from "./ConvexClientProvider";
import AppSidebar from "@/components/custom/AppSideBar";
import { SidebarProvider } from "@/components/ui/sidebar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head><title>DWARF</title></head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased w-screen h-screen`}
      >
        <ConvexClientProvider >
          <ThemeProvider
            attribute="class"
            defaultTheme="dark"
            enableSystem
            disableTransitionOnChange
          >
            <Header />
            {/* <SidebarProvider> */}
              {/* <AppSidebar /> */}
              {children}
            {/* </SidebarProvider> */}
          </ThemeProvider>
        </ConvexClientProvider>
      </body>
    </html>
  );
}
